/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    MiniPlayer: typeof import('./src/components/player/mini-player.vue')['default']
    MusicList: typeof import('./src/components/MusicList.vue')['default']
    Player: typeof import('./src/components/player/player.vue')['default']
    PlayHistory: typeof import('./src/components/player/PlayHistory.vue')['default']
    Playlist: typeof import('./src/components/player/playlist.vue')['default']
    PlaylistDetailPage: typeof import('./src/components/playlistDetail/PlaylistDetailPage.vue')['default']
    Playlists: typeof import('./src/components/Playlists.vue')['default']
    ProgressBar: typeof import('./src/components/player/progress-bar.vue')['default']
    ProgressCircle: typeof import('./src/components/player/progress-circle.vue')['default']
    RecommendedListPage: typeof import('./src/components/RecommendedListPage/RecommendedListPage.vue')['default']
    Result: typeof import('./src/components/search/result.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scroll: typeof import('./src/components/scroll/scroll.vue')['default']
    ScrollY: typeof import('./src/components/scrollY/scrollY.vue')['default']
    Search: typeof import('./src/components/search/search.vue')['default']
    SearchHistory: typeof import('./src/components/search/search-history.vue')['default']
    SearchInput: typeof import('./src/components/search/search-input.vue')['default']
    SingerList: typeof import('./src/components/SingerList.vue')['default']
    Slider: typeof import('./src/components/slider/slider.vue')['default']
    SongView: typeof import('./src/components/SongView.vue')['default']
    Suggest: typeof import('./src/components/search/suggest.vue')['default']
    TabsView: typeof import('./src/components/TabsView.vue')['default']
    TopList: typeof import('./src/components/TopList.vue')['default']
  }
}
