/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    MusicList: typeof import('./src/components/MusicList.vue')['default']
    Player: typeof import('./src/components/player/player.vue')['default']
    ProgressBar: typeof import('./src/components/player/progress-bar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scroll: typeof import('./src/components/scroll/scroll.vue')['default']
    Singer: typeof import('./src/components/Singer.vue')['default']
    Slider: typeof import('./src/components/slider/slider.vue')['default']
    SongView: typeof import('./src/components/SongView.vue')['default']
    TabsView: typeof import('./src/components/TabsView.vue')['default']
  }
}
